 package com.aaq.col.clases.webservices.wscabina.siniestro;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@SuppressWarnings("all")
/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-08-11T14:54:45.882-05:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(targetNamespace = "http://webservices.ws.cabina.qualitas.com/", name = "WSSiniestroService")
@XmlSeeAlso({ ObjectFactory.class })
public interface WSSiniestroService {

	@WebResult(name = "resultadoApertura", targetNamespace = "")
	@RequestWrapper(localName = "aperturaEstimacion", targetNamespace = "http://webservices.ws.cabina.qualitas.com/", className = "com.jmfg.siicaserver.system.webservices.clientes.jaxb.wscabina.siniestro.AperturaEstimacion")
	@WebMethod
	@ResponseWrapper(localName = "aperturaEstimacionResponse", targetNamespace = "http://webservices.ws.cabina.qualitas.com/", className = "com.jmfg.siicaserver.system.webservices.clientes.jaxb.wscabina.siniestro.AperturaEstimacionResponse")
	public com.aaq.col.clases.webservices.wscabina.siniestro.ResultadoAperturaEstimacion aperturaEstimacion(
			@WebParam(name = "reporte", targetNamespace = "") java.lang.String reporte,
			@WebParam(name = "Estimaciones", targetNamespace = "") java.util.List<com.aaq.col.clases.webservices.wscabina.siniestro.AperturaReserva> estimaciones,
			@WebParam(name = "cveUsuario", targetNamespace = "") java.lang.String cveUsuario);
}
