 package com.aaq.col.clases.webservices.wscabina.reporte;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@SuppressWarnings("all")
/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-06-25T12:51:56.554-05:00
 * Generated source version: 3.0.0
 *
 */
@WebService(targetNamespace = "http://webservices.ws.cabina.qualitas.com/", name = "WSReporteService")
@XmlSeeAlso({ ObjectFactory.class })
public interface WSReporteService {

	@WebMethod
	@RequestWrapper(localName = "asignaAjustador", targetNamespace = "http://webservices.ws.cabina.qualitas.com/", className = "com.aaq.col.clases.webservices.wscabina.reporte.AsignaAjustador")
	@ResponseWrapper(localName = "asignaAjustadorResponse", targetNamespace = "http://webservices.ws.cabina.qualitas.com/", className = "com.aaq.col.clases.webservices.wscabina.reporte.AsignaAjustadorResponse")
	@WebResult(name = "resultado", targetNamespace = "")
	public com.aaq.col.clases.webservices.wscabina.reporte.Resultado asignaAjustador(
			@WebParam(name = "numeroReporte", targetNamespace = "") java.lang.String numeroReporte,
			@WebParam(name = "claveAjustador", targetNamespace = "") java.lang.String claveAjustador);

	@WebMethod
	@RequestWrapper(localName = "getListaReportes", targetNamespace = "http://webservices.ws.cabina.qualitas.com/", className = "com.aaq.col.clases.webservices.wscabina.reporte.GetListaReportes")
	@ResponseWrapper(localName = "getListaReportesResponse", targetNamespace = "http://webservices.ws.cabina.qualitas.com/", className = "com.aaq.col.clases.webservices.wscabina.reporte.GetListaReportesResponse")
	@WebResult(name = "ListaReportes", targetNamespace = "")
	public com.aaq.col.clases.webservices.wscabina.reporte.ListaReportes getListaReportes(
			@WebParam(name = "ajustador", targetNamespace = "") java.lang.String ajustador,
			@WebParam(name = "fechaInico", targetNamespace = "") javax.xml.datatype.XMLGregorianCalendar fechaInico,
			@WebParam(name = "fechaFin", targetNamespace = "") javax.xml.datatype.XMLGregorianCalendar fechaFin);

	@WebMethod
	@RequestWrapper(localName = "datosArca", targetNamespace = "http://webservices.ws.cabina.qualitas.com/", className = "com.aaq.col.clases.webservices.wscabina.reporte.DatosArca")
	@ResponseWrapper(localName = "datosArcaResponse", targetNamespace = "http://webservices.ws.cabina.qualitas.com/", className = "com.aaq.col.clases.webservices.wscabina.reporte.DatosArcaResponse")
	@WebResult(name = "Resultado", targetNamespace = "")
	public com.aaq.col.clases.webservices.wscabina.reporte.Resultado datosArca(
			@WebParam(name = "requestArca", targetNamespace = "") com.aaq.col.clases.webservices.wscabina.reporte.RequestArca requestArca);

	@WebMethod
	@RequestWrapper(localName = "getReportes", targetNamespace = "http://webservices.ws.cabina.qualitas.com/", className = "com.aaq.col.clases.webservices.wscabina.reporte.GetReportes")
	@ResponseWrapper(localName = "getReportesResponse", targetNamespace = "http://webservices.ws.cabina.qualitas.com/", className = "com.aaq.col.clases.webservices.wscabina.reporte.GetReportesResponse")
	@WebResult(name = "getReportesResultado", targetNamespace = "")
	public com.aaq.col.clases.webservices.wscabina.reporte.GetReportesResultado getReportes(
			@WebParam(name = "numeroReporte", targetNamespace = "") java.lang.String numeroReporte,
			@WebParam(name = "numeroSiniesto", targetNamespace = "") java.lang.String numeroSiniesto,
			@WebParam(name = "numeroPoliza", targetNamespace = "") java.lang.String numeroPoliza);

	@WebMethod
	@RequestWrapper(localName = "datosPemex", targetNamespace = "http://webservices.ws.cabina.qualitas.com/", className = "com.aaq.col.clases.webservices.wscabina.reporte.DatosPemex")
	@ResponseWrapper(localName = "datosPemexResponse", targetNamespace = "http://webservices.ws.cabina.qualitas.com/", className = "com.aaq.col.clases.webservices.wscabina.reporte.DatosPemexResponse")
	@WebResult(name = "Resultado", targetNamespace = "")
	public com.aaq.col.clases.webservices.wscabina.reporte.Resultado datosPemex(
			@WebParam(name = "requestPemes", targetNamespace = "") com.aaq.col.clases.webservices.wscabina.reporte.RequestPemex requestPemes);
}
